env:
  - GO111MODULE=on
  - CGO_ENABLED=1
builds:
  - id: virtengine-darwin-amd64
    binary: virtengine
    main: ./cmd/virtengine
    goarch:
      - amd64
    goos:
      - darwin
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -trimpath
      - -mod=readonly
      - "{{ .Env.BUILD_FLAGS }}"
    ldflags:
      - "{{ .Env.LD_FLAGS }}"
      - -linkmode=external
  - id: virtengine-darwin-arm64
    binary: virtengine
    main: ./cmd/virtengine
    goarch:
      - arm64
    goos:
      - darwin
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
    flags:
      - -trimpath
      - -mod=readonly
      - "{{ .Env.BUILD_FLAGS }}"
    ldflags:
      - "{{ .Env.LD_FLAGS }}"
      - -linkmode=external
  - id: virtengine-linux-amd64
    binary: virtengine
    main: ./cmd/virtengine
    goarch:
      - amd64
    goos:
      - linux
    flags:
      - "{{ .Env.BUILD_FLAGS }}"
      - -trimpath
      - -mod=readonly
    ldflags:
      - "{{ .Env.LD_FLAGS }}"
      - -extldflags "-lc -lrt -lpthread --static"
      - -linkmode=external
  - id: virtengine-linux-arm64
    binary: virtengine
    main: ./cmd/virtengine
    goarch:
      - arm64
    goos:
      - linux
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    flags:
      - "{{ .Env.BUILD_FLAGS }}"
      - -trimpath
      - -mod=readonly
    ldflags:
      - "{{ .Env.LD_FLAGS }}"
      - -extldflags "-lc -lrt -lpthread --static"
      - -linkmode=external
  - id: virtengine-windows-amd64
    binary: virtengine
    main: ./cmd/virtengine
    goarch:
      - amd64
    goos:
      - windows
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    flags:
      - "{{ .Env.BUILD_FLAGS }}"
      - -trimpath
      - -mod=readonly
      - -buildmode=exe
    ldflags:
      - "{{ .Env.LD_FLAGS }}"
      - -linkmode=external
archives:
  - id: virtengine
    builds:
      - virtengine-darwin-amd64
      - virtengine-darwin-arm64
      - virtengine-linux-amd64
      - virtengine-linux-arm64
      - virtengine-windows-amd64
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    format: zip
    files:
      - none*

dockers:
  - ids:
      - virtengine-linux-amd64
    dockerfile: _build/Dockerfile.virtengine
    goos: linux
    goarch: amd64
    image_templates:
      - 'ghcr.io/virtengine/virtengine:{{if eq .Env.MAINNET "true"}}stable{{else}}latest{{end}}'
      - 'ghcr.io/virtengine/virtengine:{{ .ShortCommit }}'
      - 'ghcr.io/virtengine/virtengine:{{ .Version }}'
brews:
  - name: "{{ .Env.HOMEBREW_NAME }}"
    tap:
      owner: virtengine
      name: homebrew-tap
    homepage: "https://virtengine.com"
    description: "Blockchain-powered decentralized compute platform"
    custom_block: |
      {{ .Env.HOMEBREW_CUSTOM }}
    install: |
      bin.install "virtengine"

nfpms:
  - vendor: "Overclock Labs Inc."
    homepage: "http://virtengine.com"
    maintainer: "VirtEngine Network <hello@virtengine.network>"
    formats:
      - deb
      - rpm
    license: Apache 2.0

release:
  github:
    owner: virtengine
    name: virtengine
  prerelease: auto
  draft: false
