bases:
  # - github.com/virtengine/virtengine/_docs/kustomize/virtengine-provider?ref=boz/kustomize
  - ../../../../_docs/kustomize/virtengine-provider

namespace: virtengine-services

configMapGenerator:

  ##
  # cosmos-sdk client (config.toml) options
  ##
  - name: virtengine-client-config
    behavior: merge
    literals:
      - node=http://virtengine-node:26657
      - chain-id=local

  ##
  # VirtEngine provider service option overrides
  ##
  - name: virtengine-provider-config
    behavior: merge
    literals:
      - ingress-domain=app.localhost
      - cluster-public-hostname=app.localhost
      - cluster-node-port-quantity=100
      - bid-price-strategy=randomRange
      # - ingress-static-hosts=false

patchesJson6902:

  ##
  #  Configure gateway host in `gateway-host.yaml`.  Its value
  #  should be the hostname from the on-chain Provider.HostURI
  #  field.
  ##

  - path: gateway-host.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: virtengine-provider
  - path: docker-image.yaml
    target:
      kind: Deployment
      group: apps
      name: virtengine-provider
      version: v1

secretGenerator:

  ##
  # Account key material
  ##

  - name: virtengine-provider-keys
    behavior: replace
    files:
      - cache/key.txt
      - cache/key-pass.txt
      - cache/provider-cert.pem
